webdriver.driver=appium
#webdriver.timeouts.implicitlywait=1000
webdriver.wait.for.timeout=10000
serenity.restart.browser.for.each=example
serenity.timeout=10000
serenity.report.encoding=utf8
serenity.take.screenshots=FOR_EACH_ACTION
serenity.reports.show.step.details=true
feature.file.encoding=utf8
feature.file.language=es
appium.autoGrantPermissions=true
#Limpia los datos de la app antes de iniciar
appium.noReset=false
#Desinstala y reinstala la app ? borra storage/cache por completo
appium.fullReset=false
appium.autoAcceptAlerts=true
appium.clearDeviceLogsOnStart = false
appium.unicodeKeyboard = true
appium.resetKeyboard = true
appium.newCommandTimeout = 300
appium.language =
appium.locale =
appium.networkSpeed = full
serenity.logging=VERBOSE
serenity.project.name=AppiumTest
appium.settings[waitForIdleTimeout] = 100
appium.settings[allowInvisibleElements] = true
#appium.ensureWebviewsHavePages=true
appium.uiautomator2ServerInstallTimeout=120000
appium.uiautomator2ServerLaunchTimeout=120000
